steps:
# Build the container image for test
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'test_runner', '.', '--target', 'test']

# test
- name: 'test_runner'

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}:${SHORT_SHA}', '.', '--target', 'production']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_APP_NAME}:$SHORT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', '${_APP_NAME}-${_ENV}${_PR_NUMBER}',
    '--image', 'gcr.io/$PROJECT_ID/${_APP_NAME}:$SHORT_SHA',
    '--region', 'asia-northeast1',
    '--platform', 'managed'
    ]

substitutions:
  _APP_NAME: 'poetry-docker-build-and-run'
  _ENV: 'dev'

