steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}:${SHORT_SHA}', '.', '--target', 'production']
  images: ['gcr.io/$PROJECT_ID/${_APP_NAME}:$SHORT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', '${_APP_NAME}-${_ENV}',
    '--image', 'gcr.io/$PROJECT_ID/${_APP_NAME}:$SHORT_SHA',
    '--region', 'asia-northeast1',
    '--platform', 'managed'
    ]

substitutions:
  _APP_NAME: 'poetry-docker-build-and-run'
  _ENV: 'dev'

