version: '3.3'
services:
  poetry-docker-build-and-run:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "18001:18001"
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    command: >
      bash -c "uvicorn --host 0.0.0.0 --port 18001 --reload poetry_docker_build_and_run.main:app"
